MACRO(macro_get_files_without_extension result curdir)
    file(GLOB_RECURSE FILES ${curdir})
    foreach(FILE ${FILES})
        get_filename_component(FILENAME ${FILE} NAME)
        if(${FILENAME} MATCHES "^[^.]+$")
            LIST(APPEND FILELIST ${FILE})
        endif()
    endforeach()
    set(${result} ${FILELIST})
ENDMACRO()

MACRO(macro_subdir_list result curdir)
    file(GLOB children RELATIVE ${curdir} ${curdir}/*)
    set(dirlist "")
    foreach(child ${children})
    if(IS_DIRECTORY ${curdir}/${child})
        LIST(APPEND dirlist ${child})
    endif()
    endforeach()
    set(${result} ${dirlist})
ENDMACRO()

MACRO(macro_setup_launcher LAUNCHER_NAME)

    MESSAGE(STATUS "${Green}Building executable : ${LAUNCHER_NAME} ${ColourReset}")

    ADD_EXECUTABLE(${LAUNCHER_NAME} ${SOURCES} ${HEADERS} ${RESOURCES})

    TARGET_LINK_LIBRARIES(${LAUNCHER_NAME} PRIVATE ${LIBRARIES})
    IF(LIBRARIES_OPTIMIZED)
        FOREACH(LIBOPT ${LIBRARIES_OPTIMIZED})
            TARGET_LINK_LIBRARIES(${LAUNCHER_NAME} optimized ${LIBOPT})
        ENDFOREACH(LIBOPT)
    ENDIF(LIBRARIES_OPTIMIZED)

    IF(LIBRARIES_DEBUG)
        FOREACH(LIBDEBUG ${LIBRARIES_DEBUG})
            TARGET_LINK_LIBRARIES(${LAUNCHER_NAME} debug ${LIBDEBUG})
        ENDFOREACH(LIBDEBUG)
    ENDIF(LIBRARIES_DEBUG)

    SET_TARGET_PROPERTIES(${LAUNCHER_NAME} PROPERTIES PROJECT_LABEL "Launcher ${LAUNCHER_NAME}")
    SET_TARGET_PROPERTIES(${LAUNCHER_NAME} PROPERTIES DEBUG_OUTPUT_NAME "${LAUNCHER_NAME}${CMAKE_DEBUG_POSTFIX}")
    SET_TARGET_PROPERTIES(${LAUNCHER_NAME} PROPERTIES RELEASE_OUTPUT_NAME "${LAUNCHER_NAME}${CMAKE_RELEASE_POSTFIX}")
    SET_TARGET_PROPERTIES(${LAUNCHER_NAME} PROPERTIES RELWITHDEBINFO_OUTPUT_NAME "${LAUNCHER_NAME}${CMAKE_RELWITHDEBINFO_POSTFIX}")
    SET_TARGET_PROPERTIES(${LAUNCHER_NAME} PROPERTIES MINSIZEREL_OUTPUT_NAME "${LAUNCHER_NAME}${CMAKE_MINSIZEREL_POSTFIX}")
    SET_TARGET_PROPERTIES(${LAUNCHER_NAME} PROPERTIES FOLDER CMAKE_RUNTIME_OUTPUT_DIRECTORY)

    #Deploy binary files
    FOREACH(BIN ${BIN_PATH})
        INSTALL(TARGETS ${LAUNCHER_NAME}
                RUNTIME DESTINATION ${BIN}
                )
    ENDFOREACH()

ENDMACRO(SETUP_LAUNCHER)
